# -*- coding: utf-8 -*-
"""vibewise_xgboost_generous.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lNZU8XrfC51ENgFgTCh19H1jN7DJeXsD

# XGBoost Classification

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
import pickle

"""## Importing the dataset"""

from sklearn.preprocessing import LabelEncoder
dataset = pd.read_csv('xgb_imputed_semi_bin_genreless.csv', encoding='utf-8')
#print(type(dataset['genre_1'].to_numpy()))
#dataset['genre_1'] = LabelEncoder().fit_transform(dataset['genre_1'].to_numpy())
X = dataset.iloc[:,2:-1]
#print(type(X['genre_1']))
encoder = LabelEncoder()
#print(X['genre_1'])
#print(X)
numpy_mood_1 = dataset.iloc[:,2:]['mood_1'].to_numpy()
print(set(numpy_mood_1))

enc_m1 = encoder.fit_transform(numpy_mood_1)
y = enc_m1
#print(set(y))

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
#list(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
set_y = set(y)
print(set_y)

"""## Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""## Training the Logistic Regression model on the Training set"""

from xgboost import XGBClassifier
eval_set = [(X_test, y_test)]
model = XGBClassifier()
#print("y-train",set(y_train))
#print("y-test",set(y_test))
#model.fit(X_train,y_train,early_stopping_rounds=10,eval_metric="mlogloss",eval_set=[(X_test,y_test)],verbose=False)

"""## Pickle the Model"""

filename = 'xgboost_model.sav'
#pickle.dump(model, open(filename, 'wb'))
pickle.dump(encoder, open('mood_encoder.sav', 'wb'))